// bundled instrument packs: generated by `python3 -m nuxdsp web` from instruments/, do not edit.
globalThis.NUXDSP_PACKS = [{"name":"Cat Piano","name_pl":"Kocie piano","cents":-9.0,"author":"Meku A","source":"Freesound.org, via creazilla.com (Cat Piano Note C), attack trimmed","license":"CC0 1.0 (public domain)","id":"cat_piano","zones":29,"keys":[24,108]}];
