"""Export target data for the offline web patcher (web/index.html + web/patcher.js, hand-written).

Each supported firmware gets web/targets/<id>.js. It contains only the words *we* write (our code,
our hook instructions, our string characters), never original firmware words: the user's file is
identified by its SHA-256. Parameters are exported as per-value word tables computed by the real
builder, so the page cannot drift from the CLI. Regenerating needs the official file of that target
only, so each model can be maintained by whoever owns it.
"""
import base64
import json
import os
import re

from . import container, instrument, patcher

WEB_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "web")
BEGIN, END = "<!-- targets:begin (generated by python3 -m nuxdsp web) -->", "<!-- targets:end -->"


def patch_words(image, fwmap, p, params=None):
    owner = {}
    need = [patcher.load(r, fwmap) for r in p.requires]  # built along, their words are their own
    out, _ = patcher.build(image, fwmap, need + [p], params, owner_out=owner)
    new = container.words(out)
    return {a: new[a] for a in sorted(owner) if owner[a] == p.name}  # the checksum word is recomputed in JS


def export_data(image, fwmap, names=None):
    data = {"id": fwmap.id, "device": fwmap.device, "firmware": fwmap.firmware, "input": fwmap.input,
            "output": fwmap.output, "download": fwmap.download, "sha256": fwmap.sha256, "words": len(container.words(image)),
            "patches": []}
    for n in names or patcher.available(fwmap):
        p = patcher.load(n, fwmap)
        base = patch_words(image, fwmap, p)
        entry = {"name": p.name, "title": p.title, "words": base, "params": [], "requires": p.requires,
                 "default": p.name in fwmap.defaults}
        seen = set()
        for prm in p.params:
            values = {}
            for v in range(prm.lo, prm.hi + 1):
                w = patch_words(image, fwmap, p, {prm.name: v})
                if set(w) - set(base) or set(base) - set(w):
                    raise patcher.PatchError("%s: %s changes which words are written" % (p.name, prm.name))
                values[v] = {a: x for a, x in w.items() if x != base[a]}
            touched = {a for d in values.values() for a in d}
            if touched & seen:
                raise patcher.PatchError("%s: parameters share words, not exportable" % p.name)
            seen |= touched
            entry["params"].append({"name": prm.name, "default": prm.default, "lo": prm.lo, "hi": prm.hi,
                                    "desc": prm.desc, "values": values})
        data["patches"].append(entry)
    if fwmap.soundbank and "custom_voices" in patcher.available(fwmap):
        from . import soundbank
        syms = fwmap.symbols()  # addresses only: the tables are read from the user's own file
        data["voices"] = {"soundbank": fwmap.soundbank, "cvTab": soundbank.table_addr(fwmap), "max": 4,
                          "ramdata": fwmap.ramdata[0], "voiceBanks": syms["voice_banks"],
                          "soundNames": syms["sound_names"]}
    return data


def target_js(image, fwmap, names=None):
    data = json.dumps(export_data(image, fwmap, names), separators=(",", ":"))
    return ("// %s %s: generated by `python3 -m nuxdsp web` from targets/%s, do not edit.\n"
            "(globalThis.NUXDSP_TARGETS = globalThis.NUXDSP_TARGETS || []).push(%s);\n"
            % (fwmap.device, fwmap.firmware, fwmap.id, data))


def pack_js(name):
    """web/instruments/<name>.js: a bundled SoundFont, loaded by the page when chosen (works from file:// too)."""
    with open(instrument.bundled(name), "rb") as f:
        data = f.read()
    return ("// instrument %s.sf2: generated by `python3 -m nuxdsp web` from instruments/, do not edit.\n"
            "(globalThis.NUXDSP_PACK_DATA = globalThis.NUXDSP_PACK_DATA || {})[%s] = \"%s\";\n"
            % (name, json.dumps(name), base64.b64encode(data).decode()))


def packs_index_js():
    """web/instruments/index.js: what the bundled instruments are, without their samples."""
    from . import sf2
    out = []
    for n in instrument.bundled_names():
        sf = sf2.load(instrument.bundled(n))
        out.append(dict(sf.info, id=n, name_pl=instrument.bundled_meta(n).get("name_pl", ""),
                        size=os.path.getsize(instrument.bundled(n))))
    return ("// bundled instruments: generated by `python3 -m nuxdsp web` from instruments/, do not edit.\n"
            "globalThis.NUXDSP_PACKS = %s;\n" % json.dumps(out, ensure_ascii=False, separators=(",", ":")))


def write_packs(web_dir=WEB_DIR):
    d = os.path.join(web_dir, "instruments")
    os.makedirs(d, exist_ok=True)
    files = {"index.js": packs_index_js()}
    files.update({n + ".js": pack_js(n) for n in instrument.bundled_names()})
    for f, text in files.items():
        with open(os.path.join(d, f), "w", encoding="utf-8") as fh:
            fh.write(text)
    return sorted(files)


def update_index(web_dir=WEB_DIR):
    """List every web/targets/*.js in index.html. Returns the target ids."""
    ids = sorted(f[:-3] for f in os.listdir(os.path.join(web_dir, "targets")) if f.endswith(".js"))
    path = os.path.join(web_dir, "index.html")
    with open(path, encoding="utf-8") as f:
        page = f.read()
    tags = "".join('<script src="targets/%s.js"></script>\n' % i for i in ids)
    page, n = re.subn(re.escape(BEGIN) + ".*?" + re.escape(END), lambda _: BEGIN + "\n" + tags + END, page,
                      flags=re.S)
    if n != 1:
        raise ValueError("%s: target markers not found" % path)
    with open(path, "w", encoding="utf-8") as f:
        f.write(page)
    return ids


def write_target(image, fwmap, web_dir=WEB_DIR, names=None):
    path = os.path.join(web_dir, "targets", fwmap.id + ".js")
    with open(path, "w", encoding="utf-8") as f:
        f.write(target_js(image, fwmap, names))
    update_index(web_dir)
    return path
