// nuxdsp web patcher core: identification and patching. Runs in the browser and under node (tests).
// Target data (web/targets/*.js) is generated by `python3 -m nuxdsp web` and contains only the words
// our patches write, never vendor code: the user's own official file is identified by its SHA-256.
var TARGETS = (globalThis.NUXDSP_TARGETS = globalThis.NUXDSP_TARGETS || []);
// --- SHA-256 (fallback when crypto.subtle is unavailable, e.g. some file:// setups) ---
function sha256js(bytes) {
  const K = new Uint32Array([0x428a2f98,0x71374491,0xb5c0fbcf,0xe9b5dba5,0x3956c25b,0x59f111f1,0x923f82a4,0xab1c5ed5,
    0xd807aa98,0x12835b01,0x243185be,0x550c7dc3,0x72be5d74,0x80deb1fe,0x9bdc06a7,0xc19bf174,0xe49b69c1,0xefbe4786,
    0x0fc19dc6,0x240ca1cc,0x2de92c6f,0x4a7484aa,0x5cb0a9dc,0x76f988da,0x983e5152,0xa831c66d,0xb00327c8,0xbf597fc7,
    0xc6e00bf3,0xd5a79147,0x06ca6351,0x14292967,0x27b70a85,0x2e1b2138,0x4d2c6dfc,0x53380d13,0x650a7354,0x766a0abb,
    0x81c2c92e,0x92722c85,0xa2bfe8a1,0xa81a664b,0xc24b8b70,0xc76c51a3,0xd192e819,0xd6990624,0xf40e3585,0x106aa070,
    0x19a4c116,0x1e376c08,0x2748774c,0x34b0bcb5,0x391c0cb3,0x4ed8aa4a,0x5b9cca4f,0x682e6ff3,0x748f82ee,0x78a5636f,
    0x84c87814,0x8cc70208,0x90befffa,0xa4506ceb,0xbef9a3f7,0xc67178f2]);
  const H = new Uint32Array([0x6a09e667,0xbb67ae85,0x3c6ef372,0xa54ff53a,0x510e527f,0x9b05688c,0x1f83d9ab,0x5be0cd19]);
  const n = bytes.length, total = Math.ceil((n + 9) / 64) * 64;
  const m = new Uint8Array(total); m.set(bytes); m[n] = 0x80;
  const dv = new DataView(m.buffer);
  dv.setUint32(total - 8, Math.floor(n / 0x20000000)); dv.setUint32(total - 4, (n * 8) >>> 0);
  const w = new Uint32Array(64), r = (x, s) => (x >>> s) | (x << (32 - s));
  for (let o = 0; o < total; o += 64) {
    for (let i = 0; i < 16; i++) w[i] = dv.getUint32(o + 4 * i);
    for (let i = 16; i < 64; i++) {
      const s0 = r(w[i-15], 7) ^ r(w[i-15], 18) ^ (w[i-15] >>> 3), s1 = r(w[i-2], 17) ^ r(w[i-2], 19) ^ (w[i-2] >>> 10);
      w[i] = (w[i-16] + s0 + w[i-7] + s1) >>> 0;
    }
    let [a, b, c, d, e, f, g, h] = H;
    for (let i = 0; i < 64; i++) {
      const t1 = (h + (r(e, 6) ^ r(e, 11) ^ r(e, 25)) + ((e & f) ^ (~e & g)) + K[i] + w[i]) >>> 0;
      const t2 = ((r(a, 2) ^ r(a, 13) ^ r(a, 22)) + ((a & b) ^ (a & c) ^ (b & c))) >>> 0;
      h = g; g = f; f = e; e = (d + t1) >>> 0; d = c; c = b; b = a; a = (t1 + t2) >>> 0;
    }
    H[0] += a; H[1] += b; H[2] += c; H[3] += d; H[4] += e; H[5] += f; H[6] += g; H[7] += h;
  }
  return Array.from(H, x => x.toString(16).padStart(8, "0")).join("");
}
async function sha256(bytes) {
  try {
    const d = await crypto.subtle.digest("SHA-256", bytes);
    return Array.from(new Uint8Array(d), x => x.toString(16).padStart(2, "0")).join("");
  } catch (e) { return sha256js(bytes); }
}

// --- container: 16-bit LE words, w[0] = 'rd', w[1..2] = length in words, sum of all words == 0 ---
function containerOk(bytes) {
  if (bytes.length < 8 || bytes.length % 2) return false;
  const dv = new DataView(bytes.buffer, bytes.byteOffset, bytes.length), n = bytes.length / 2;
  let s = 0;
  for (let i = 0; i < n; i++) s += dv.getUint16(2 * i, true);
  return dv.getUint16(0, true) === 0x6472 && (dv.getUint16(2, true) | dv.getUint16(4, true) << 16) === n && !(s & 0xffff);
}
// -> {target} for a supported official file, {dream: true} for another valid DSP container, {} otherwise
async function identify(bytes) {
  const sha = await sha256(bytes);
  const target = TARGETS.find(t => t.sha256 === sha && t.words * 2 === bytes.length);
  return {sha, target, dream: !target && containerOk(bytes)};
}
// --- patching: selection = {patchName: {PARAM: value}} -> new image bytes (tested in tests/) ---
function applyPatches(target, bytes, selection) {
  const out = new Uint8Array(bytes), dv = new DataView(out.buffer);
  const n = out.length / 2, owner = {};
  for (const p of target.patches) {
    if (!(p.name in selection)) continue;
    for (const r of p.requires || []) if (!(r in selection)) throw `${p.name} needs ${r} too`;
    const words = Object.assign({}, p.words);
    for (const prm of p.params) {
      const v = selection[p.name][prm.name] ?? prm.default;
      if (!Number.isInteger(v) || v < prm.lo || v > prm.hi) throw `${prm.name} must be ${prm.lo}..${prm.hi}`;
      Object.assign(words, prm.values[v]);
    }
    for (const [a, w] of Object.entries(words)) {
      if (owner[a]) throw `${owner[a]} and ${p.name} both modify word ${a}`;
      owner[a] = p.name; dv.setUint16(2 * a, w, true);
    }
  }
  if (!Object.keys(owner).length) throw "select at least one patch";
  let s = 0;
  for (let i = 0; i < n - 1; i++) s += dv.getUint16(2 * i, true);
  dv.setUint16(2 * (n - 1), (-s) & 0xffff, true);
  let check = 0;
  for (let i = 0; i < n; i++) check += dv.getUint16(2 * i, true);
  if ((check & 0xffff) || dv.getUint16(0, true) !== 0x6472) throw "internal error: output container invalid";
  return out;
}
