// nuxdsp web patcher core: identification and patching. Runs in the browser and under node (tests).
// Target data (web/targets/*.js) is generated by `python3 -m nuxdsp web` and contains only the words
// our patches write, never vendor code: the user's own official file is identified by its SHA-256.
var TARGETS = (globalThis.NUXDSP_TARGETS = globalThis.NUXDSP_TARGETS || []);
// --- SHA-256 (fallback when crypto.subtle is unavailable, e.g. some file:// setups) ---
function sha256js(bytes) {
  const K = new Uint32Array([0x428a2f98,0x71374491,0xb5c0fbcf,0xe9b5dba5,0x3956c25b,0x59f111f1,0x923f82a4,0xab1c5ed5,
    0xd807aa98,0x12835b01,0x243185be,0x550c7dc3,0x72be5d74,0x80deb1fe,0x9bdc06a7,0xc19bf174,0xe49b69c1,0xefbe4786,
    0x0fc19dc6,0x240ca1cc,0x2de92c6f,0x4a7484aa,0x5cb0a9dc,0x76f988da,0x983e5152,0xa831c66d,0xb00327c8,0xbf597fc7,
    0xc6e00bf3,0xd5a79147,0x06ca6351,0x14292967,0x27b70a85,0x2e1b2138,0x4d2c6dfc,0x53380d13,0x650a7354,0x766a0abb,
    0x81c2c92e,0x92722c85,0xa2bfe8a1,0xa81a664b,0xc24b8b70,0xc76c51a3,0xd192e819,0xd6990624,0xf40e3585,0x106aa070,
    0x19a4c116,0x1e376c08,0x2748774c,0x34b0bcb5,0x391c0cb3,0x4ed8aa4a,0x5b9cca4f,0x682e6ff3,0x748f82ee,0x78a5636f,
    0x84c87814,0x8cc70208,0x90befffa,0xa4506ceb,0xbef9a3f7,0xc67178f2]);
  const H = new Uint32Array([0x6a09e667,0xbb67ae85,0x3c6ef372,0xa54ff53a,0x510e527f,0x9b05688c,0x1f83d9ab,0x5be0cd19]);
  const n = bytes.length, total = Math.ceil((n + 9) / 64) * 64;
  const m = new Uint8Array(total); m.set(bytes); m[n] = 0x80;
  const dv = new DataView(m.buffer);
  dv.setUint32(total - 8, Math.floor(n / 0x20000000)); dv.setUint32(total - 4, (n * 8) >>> 0);
  const w = new Uint32Array(64), r = (x, s) => (x >>> s) | (x << (32 - s));
  for (let o = 0; o < total; o += 64) {
    for (let i = 0; i < 16; i++) w[i] = dv.getUint32(o + 4 * i);
    for (let i = 16; i < 64; i++) {
      const s0 = r(w[i-15], 7) ^ r(w[i-15], 18) ^ (w[i-15] >>> 3), s1 = r(w[i-2], 17) ^ r(w[i-2], 19) ^ (w[i-2] >>> 10);
      w[i] = (w[i-16] + s0 + w[i-7] + s1) >>> 0;
    }
    let [a, b, c, d, e, f, g, h] = H;
    for (let i = 0; i < 64; i++) {
      const t1 = (h + (r(e, 6) ^ r(e, 11) ^ r(e, 25)) + ((e & f) ^ (~e & g)) + K[i] + w[i]) >>> 0;
      const t2 = ((r(a, 2) ^ r(a, 13) ^ r(a, 22)) + ((a & b) ^ (a & c) ^ (b & c))) >>> 0;
      h = g; g = f; f = e; e = (d + t1) >>> 0; d = c; c = b; b = a; a = (t1 + t2) >>> 0;
    }
    H[0] += a; H[1] += b; H[2] += c; H[3] += d; H[4] += e; H[5] += f; H[6] += g; H[7] += h;
  }
  return Array.from(H, x => x.toString(16).padStart(8, "0")).join("");
}
async function sha256(bytes) {
  try {
    const d = await crypto.subtle.digest("SHA-256", bytes);
    return Array.from(new Uint8Array(d), x => x.toString(16).padStart(2, "0")).join("");
  } catch (e) { return sha256js(bytes); }
}

// --- container: 16-bit LE words, w[0] = 'rd', w[1..2] = length in words, sum of all words == 0 ---
function containerOk(bytes) {
  if (bytes.length < 8 || bytes.length % 2) return false;
  const dv = new DataView(bytes.buffer, bytes.byteOffset, bytes.length), n = bytes.length / 2;
  let s = 0;
  for (let i = 0; i < n; i++) s += dv.getUint16(2 * i, true);
  return dv.getUint16(0, true) === 0x6472 && (dv.getUint16(2, true) | dv.getUint16(4, true) << 16) === n && !(s & 0xffff);
}
// -> {target} for a supported official file, {dream: true} for another valid DSP container, {} otherwise
async function identify(bytes) {
  const sha = await sha256(bytes);
  const target = TARGETS.find(t => t.sha256 === sha && t.words * 2 === bytes.length);
  return {sha, target, dream: !target && containerOk(bytes)};
}
// --- patching: selection = {patchName: {PARAM: value}} -> new image bytes (tested in tests/) ---
function applyPatches(target, bytes, selection) {
  const out = new Uint8Array(bytes), dv = new DataView(out.buffer);
  const n = out.length / 2, owner = {};
  for (const p of target.patches) {
    if (!(p.name in selection)) continue;
    for (const r of p.requires || []) if (!(r in selection)) throw `${p.name} needs ${r} too`;
    const words = Object.assign({}, p.words);
    for (const prm of p.params) {
      const v = selection[p.name][prm.name] ?? prm.default;
      if (!Number.isInteger(v) || v < prm.lo || v > prm.hi) throw `${prm.name} must be ${prm.lo}..${prm.hi}`;
      Object.assign(words, prm.values[v]);
    }
    for (const [a, w] of Object.entries(words)) {
      if (owner[a]) throw `${owner[a]} and ${p.name} both modify word ${a}`;
      owner[a] = p.name; dv.setUint16(2 * a, w, true);
    }
  }
  if (!Object.keys(owner).length) throw "select at least one patch";
  return fixChecksum(out);
}
function fixChecksum(out) {
  const dv = new DataView(out.buffer, out.byteOffset, out.length), n = out.length / 2;
  let s = 0;
  for (let i = 0; i < n - 1; i++) s += dv.getUint16(2 * i, true);
  dv.setUint16(2 * (n - 1), (-s) & 0xffff, true);
  if (!containerOk(out)) throw "internal error: output container invalid";
  return out;
}

// --- added instruments (port of nuxdsp/soundbank.py and instrument.py; same bytes, tested in tests/) ---
const u16 = (d, o) => d[o] | d[o + 1] << 8, u32 = (d, o) => (u16(d, o) | u16(d, o + 2) << 16) >>> 0;
const put16 = (d, o, v) => { d[o] = v & 0xff; d[o + 1] = v >> 8 & 0xff; };
const put32 = (d, o, v) => { put16(d, o, v & 0xffff); put16(d, o + 2, v >>> 16); };
const PL_LETTERS = "ąćęłńóśźżĄĆĘŁŃÓŚŹŻ";
// --- SoundFont 2 (port of nuxdsp/sf2.py): a preset -> {name, zones: [{lo, hi, root, cents, rate, pcm, loop, key}]}
function sf2Chunks(d, o, end) {
  const out = [];
  while (o + 8 <= end) {
    const id = String.fromCharCode(...d.subarray(o, o + 4)), n = u32(d, o + 4);
    out.push([id, o + 8, n]); o += 8 + n + (n & 1);
  }
  return out;
}
const sf2Str = b => { let s = ""; for (const c of b) { if (!c) break; s += String.fromCharCode(c); } return s.trim(); };
const s16 = v => v & 0x8000 ? v - 0x10000 : v;
function parseSf2(d) {
  if (String.fromCharCode(...d.subarray(0, 4)) !== "RIFF" || String.fromCharCode(...d.subarray(8, 12)) !== "sfbk")
    throw "not a SoundFont 2 file (.sf2)";
  const lists = {}, info = {};
  for (const [id, o, n] of sf2Chunks(d, 12, d.length))
    if (id === "LIST") lists[String.fromCharCode(...d.subarray(o, o + 4))] = [o + 4, o + n];
  if (!lists.INFO || !lists.sdta || !lists.pdta) throw "incomplete SoundFont";
  for (const [id, o, n] of sf2Chunks(d, ...lists.INFO)) if (id !== "ifil") info[id] = sf2Str(d.subarray(o, o + n));
  let smpl = null;
  for (const [id, o, n] of sf2Chunks(d, ...lists.sdta)) if (id === "smpl") smpl = [o, Math.floor(n / 2)];
  if (!smpl) throw "no samples (sdta/smpl) in the SoundFont";
  const p = {};
  for (const [id, o, n] of sf2Chunks(d, ...lists.pdta)) p[id] = [o, n];
  const recs = (name, size, f) => { const [o, n] = p[name], out = [];
    for (let i = 0; i < Math.floor(n / size); i++) out.push(f(o + i * size)); return out; };
  const bag = o => [u16(d, o), u16(d, o + 2)];
  return {d, info, smpl,
    phdr: recs("phdr", 38, o => [sf2Str(d.subarray(o, o + 20)), u16(d, o + 20), u16(d, o + 22), u16(d, o + 24)]),
    pbag: recs("pbag", 4, bag), pgen: recs("pgen", 4, bag), ibag: recs("ibag", 4, bag), igen: recs("igen", 4, bag),
    inst: recs("inst", 22, o => [sf2Str(d.subarray(o, o + 20)), u16(d, o + 20)]),
    shdr: recs("shdr", 46, o => [sf2Str(d.subarray(o, o + 20)), u32(d, o + 20), u32(d, o + 24), u32(d, o + 28),
      u32(d, o + 32), u32(d, o + 36), d[o + 40], (d[o + 41] << 24) >> 24, u16(d, o + 42), u16(d, o + 44)])};
}
// [{index, bank, program, name}] sorted like the CLI's @N
function sf2Presets(sf) {
  return sf.phdr.slice(0, -1).map(([name, program, bank], index) => ({index, bank, program, name}))
    .sort((a, b) => a.bank - b.bank || a.program - b.program || a.index - b.index);
}
function sf2Zones(sf, bags, gens, first, last, term) {
  const zs = [];
  for (let b = first; b < last; b++) {
    const g = {};
    for (let k = bags[b][0]; k < bags[b + 1][0]; k++) g[gens[k][0]] = gens[k][1];
    zs.push(g);
  }
  const glob = zs.length && !(term in zs[0]) ? zs.shift() : {};
  return [glob, zs.filter(z => term in z)];
}
const sf2Range = (z, op) => z[op] === undefined ? [0, 127] : [z[op] & 0xff, z[op] >> 8];
const sf2Isect = (a, b) => { const lo = Math.max(a[0], b[0]), hi = Math.min(a[1], b[1]); return lo <= hi ? [lo, hi] : null; };
function sf2Sample(sf, iz) {
  const sid = iz[53];
  if (sid >= sf.shdr.length - 1) throw "bad sample index";
  let [name, start, end, ls, le, rate, pitch, corr, link, typ] = sf.shdr[sid];
  if (typ & 0x8000) throw "ROM samples are not supported";
  const g = op => s16(iz[op] || 0);
  start += g(0) + 32768 * g(4); end += g(1) + 32768 * g(12);
  ls += g(2) + 32768 * g(45); le += g(3) + 32768 * g(50);
  if (!(0 <= start && start < end && end <= sf.smpl[1])) throw `sample ${name} outside the sample data`;
  const o = sf.smpl[0] + 2 * start;
  return {pcm: sf.d.subarray(o, o + 2 * (end - start)), start, end, ls, le, rate, pitch, corr};
}
function sf2Zone(sf, key, iz, pz, iz2) {
  let {pcm, start, end, ls, le, rate, pitch, corr} = sf2Sample(sf, iz);
  let skey = `${iz[53]},${start},${end}`;
  if (iz2) {
    const pcm2 = sf2Sample(sf, iz2).pcm, n = Math.floor(Math.min(pcm.length, pcm2.length) / 2), m = new Uint8Array(2 * n);
    const a = new DataView(pcm.buffer, pcm.byteOffset), b = new DataView(pcm2.buffer, pcm2.byteOffset), w = new DataView(m.buffer);
    for (let i = 0; i < n; i++) w.setInt16(2 * i, (a.getInt16(2 * i, true) + b.getInt16(2 * i, true)) >> 1, true);
    pcm = m; skey += `,${iz2[53]}`;
  }
  let root = s16(iz[58] ?? 0xffff);
  if (root < 0) root = pitch;
  const cents = 100 * (s16(iz[51] || 0) + s16(pz[51] || 0)) + s16(iz[52] || 0) + s16(pz[52] || 0) + corr;
  let loop = null;
  if ((iz[54] || 0) & 1 && start <= ls && ls < le && le <= end) {
    loop = [ls - start, le - start]; pcm = pcm.subarray(0, 2 * (le - start + 1)); skey += `,loop,${ls},${le}`;
  }
  return {lo: key[0], hi: key[1], root, cents, rate, pcm, loop, key: skey};
}
function sf2Instrument(sf, preset, velocity = 100) {
  const ph = sf.phdr, name = ph[preset][0];
  if (ph[preset][2] === 120 || ph[preset][2] === 128)  // percussion: SF2 bank 128, GM2 rhythm bank 120
    throw `drum kit (bank ${ph[preset][2]}): not supported, the sound follows the keyboard`;
  const [pg, pz] = sf2Zones(sf, sf.pbag, sf.pgen, ph[preset][3], ph[preset + 1][3], 41);
  let regions = [];
  for (const z of pz) {
    const pzone = {...pg, ...z}, i = pzone[41];
    const [ig, iz] = sf2Zones(sf, sf.ibag, sf.igen, sf.inst[i][1], sf.inst[i + 1][1], 53);
    for (const z2 of iz) {
      const izone = {...ig, ...z2};
      const key = sf2Isect(sf2Range(pzone, 43), sf2Range(izone, 43)), vel = sf2Isect(sf2Range(pzone, 44), sf2Range(izone, 44));
      if (key && vel && vel[0] <= velocity && velocity <= vel[1]) regions.push([key, izone, pzone]);
    }
  }
  if (!regions.length) throw `preset ${name} has no samples at velocity ${velocity}`;
  regions = regions.filter(r => s16(r[1][56] ?? 100) === 100);  // noise layers, drum kits: same pitch on every key
  if (!regions.length) throw "same pitch on every key (drum kits, effects): not supported, the sound follows the keyboard";
  const zones = [], done = new Set();
  regions.forEach(([key, iz, pz], n) => {
    if (done.has(n)) return;
    done.add(n);
    const sh = sf.shdr[iz[53]];
    let pair = -1;
    if (sh[9] & 6) {
      pair = regions.findIndex(([k2, iz2], m) => !done.has(m) && k2[0] === key[0] && k2[1] === key[1] && iz2[53] === sh[8]);
      if (pair >= 0) done.add(pair);
    }
    zones.push(sf2Zone(sf, key, iz, pz, pair >= 0 ? regions[pair][1] : null));
  });
  // layers: each key gets the zone of the first layer that has it (as nuxdsp/sf2.py)
  const owner = [...Array(128).keys()].map(k => zones.find(z => z.lo <= k && k <= z.hi) || null), out = [];
  owner.forEach((z, k) => {
    if (!z) return;
    if (out.length && owner[k - 1] === z) out[out.length - 1].hi = k;
    else out.push({...z, lo: k, hi: k});
  });
  const seen = new Map();
  const size = out.reduce((s, z) => seen.has(z.key) ? s : (seen.set(z.key, 1), s + z.pcm.length), 0);
  return {name, zones: out, info: sf.info, size};
}
function dspWord(dsp, a) { return u16(dsp, 2 * a); }
// voices: target.voices (addresses from the map); dsp: the user's official DSP file
function voiceBanks(v, dsp) {
  const out = [];
  for (let i = 0; i < 64; i += 2) {
    const b = dspWord(dsp, v.ramdata + v.voiceBanks + i), n = dspWord(dsp, v.ramdata + v.voiceBanks + i + 1);
    if (!n) break;
    out.push([b, n]);
  }
  return out;
}
function soundNames(v, dsp) {
  const names = [];
  for (let i = 0; i < 500; i++) {
    let a = dspWord(dsp, v.ramdata + v.soundNames + i), s = "";
    while (dspWord(dsp, v.ramdata + a)) s += String.fromCharCode(dspWord(dsp, v.ramdata + a++));
    names.push(s);
  }
  return names;
}
function voiceToBankProg(banks, voice) {
  let x = voice - 1;
  for (const [b, n] of banks) { if (x >= 0 && x < n) return [b, x]; x -= n; }
  throw `sound ${voice} does not exist`;
}
function dirEntry(d, bank, prog) {
  let a = u16(d, 0x252 + 2 * prog) * 2;
  while (u32(d, a) !== 0xffffffff) { if (d[a] === bank) return a; a += 4; }
  throw `no instrument for bank ${bank} program ${prog}`;
}
const instrumentAddr = (d, a) => (d[a + 1] * 0x10000 + u16(d, a + 2)) * 2;
function zoneAddrs(d, inst) {
  const page = Math.floor(inst / 2 / 0x10000) * 0x10000, out = [];
  for (let o = inst + 4; ; o += 6) {
    out.push((page + u16(d, o + 4)) * 2);
    if (d[o + 3] === 0xff) return out;
  }
}
function findSampleBlock(d, z) {
  for (let o = z; o < z + 0x60; o++)
    if (d[o + 1] <= 1 && d[o + 4] === 1 && !d[o + 6] && !d[o + 7] && !d[o + 9] && !d[o + 15] && d[o + 18] === 0x0e && d[o + 19] === 0x7f)
      return o;
  throw "no sample block in the template zone";
}
function zoneRecord(d, z) {
  const pageB = Math.floor(z / 2 / 0x10000) * 0x20000, sb = findSampleBlock(d, z);
  let marker = z;
  while (!(d[marker] === 0xf0 && d[marker + 1] === 0xb5)) marker++;
  const offs = [0];
  for (let o = 4; o < marker - z + 2; o += 2) offs.push(o);
  const ptrs = offs.map(o => u16(d, z - 2 + o) * 2 + pageB), top = Math.max(...ptrs);
  if (d[top + 2] !== 3 || d[top + 3] !== 4) throw "unexpected template zone layout";
  const end = top + 26;
  if (ptrs.some(p => p < z - 2 || p >= end)) throw "template zone points outside itself";
  const rec = d.slice(z - 2, end);
  if (rec[sb - z + 2 - 4] & 0x40) throw "template zone does not follow the keyboard";
  return {rec, offs, pageB, sbOff: sb - (z - 2)};
}
function setAddrs(r, o, S, L, E) {
  const hi = Math.floor(S / 0x1000000);
  if (Math.floor(L / 0x1000000) !== hi || Math.floor(E / 0x1000000) !== hi) throw "sample crosses a 16M-word boundary";
  r[o] = (r[o] & 0x3f) | ((hi & 3) << 6); r[o + 1] = hi >> 2;
  put16(r, o + 2, (L >>> 8) & 0xffff); r[o + 5] = L & 0xff;
  r[o + 8] = S & 0xff; put16(r, o + 10, (S >>> 8) & 0xffff);
  r[o + 14] = E & 0xff; put16(r, o + 16, (E >>> 8) & 0xffff);
}
// even: the vendor's tunings all are, and an odd one breaks the synth until power-off (bit 0 is no tuning bit)
const tuneValue = (midi, cents, rate) =>
  2 * Math.round(128 * (-83.996 - 12 * Math.log2(440 * 2 ** ((midi - 69) / 12) * 2 ** (cents / 1200) / rate)));
// items: [{pack: sf2Instrument(...), voice}] -> new soundbank bytes; bank: the user's official soundbank file
async function addInstruments(target, dsp, bank, items) {
  const v = target.voices, d = bank, FB = 0x80000;
  if (await sha256(bank) !== v.soundbank.sha256) throw `not the official ${v.soundbank.name} (SHA-256 mismatch)`;
  if (new Set(items.map(i => i.voice)).size !== items.length) throw "two instruments for the same sound";
  const banks = voiceBanks(v, dsp);
  const templates = {};
  for (const kind of ["template", "template_loop"]) {      // one-shots, and instruments with loops
    const [tv, tzone] = v.soundbank[kind] || v.soundbank.template;
    const tinst = instrumentAddr(d, dirEntry(d, ...voiceToBankProg(banks, tv)));
    const tz = zoneAddrs(d, tinst)[tzone];
    templates[kind] = {tz, hdr: d.slice(tinst, tinst + 4), ...zoneRecord(d, tz)};
  }
  let tail = -1;
  const mark = new TextEncoder().encode("PackNameDate:");
  for (let i = d.length - mark.length; i >= 0 && tail < 0; i--)
    if (mark.every((c, j) => d[i + j] === c)) tail = i;
  if (tail < 0) throw "soundbank trailer not found";
  const align = n => Math.ceil(n / 0x800) * 0x800;
  // samples: appended at the end, each with E on the last word of a 256-word block (as the vendor's)
  let pos = tail;
  const layout = items.map(({pack}) => {
    pos = align(pos);
    const seen = new Map();
    return pack.zones.map(z => {
      if (seen.has(z.key)) return seen.get(z.key);
      const end = z.loop ? z.loop[1] : z.pcm.length / 2 + 63;  // E - S
      let S = FB + (pos + 4) / 2;
      pos += 2 * (((255 - (S + end)) % 256 + 256) % 256);
      const start = pos + 4; S = FB + start / 2;
      pos = start + z.pcm.length + (z.loop ? 0 : 128);       // two zero guard words; one-shots: 64 silent ones
      const a = {start, pcm: z.pcm, silence: z.loop ? 0 : 128,
                 addr: z.loop ? [S, S + z.loop[0], S + z.loop[1]] : [S, S + end - 43, S + end]};
      seen.set(z.key, a);
      return a;
    });
  });
  const len = align(pos);
  const out = new Uint8Array(len + d.length - tail);
  out.set(d.subarray(0, tail)); out.set(d.subarray(tail), len);
  for (let i = tail; i < len; i += 2) { out[i] = 0xef; out[i + 1] = 0xad; }
  const placed = layout.map(zs => zs.map(a => {
    out.fill(0, a.start - 4, a.start + a.pcm.length + a.silence);
    out.set(a.pcm, a.start);
    return a.addr;
  }));
  put32(out, 8, FB + len / 2); put32(out, 0x9c, FB + len / 2);
  items.forEach(({pack, voice}, k) => {
    const base = (u32(out, 0xa6) - FB) * 2 + 0x10, page = Math.floor(base / 0x20000), n = pack.zones.length;
    if (n < 1 || n > 127) throw `${pack.name}: ${n} zones (1..127)`;
    const T = templates[pack.zones.some(z => z.loop) ? "template_loop" : "template"], tz = T.tz;
    const zoneAt = base + 4 + 6 * n + 2, recLen = T.rec.length, size = 4 + 6 * n + 2 + n * recLen;
    if (base + size > (page + 1) * 0x20000 || out.subarray(base - 0x10, base + size).some(b => b !== 0x5e && b !== 0xd0))
      throw "no free room for the instrument in the parameter page";
    const inst = new Uint8Array(size);
    inst.set(T.hdr); inst[2] = 0x80 | n;
    let hi = 0;
    pack.zones.forEach((zn, i) => {
      const zstart = zoneAt + i * recLen, lo = hi, e = 4 + 6 * i;
      hi = i === n - 1 ? 0xff : zn.hi;
      inst.set([i ? 0 : 0x80, lo, 0x7f, hi], e); put16(inst, e + 4, ((zstart + 2) / 2) & 0xffff);
      const z = T.rec.slice();
      for (const o of T.offs) {
        const nw = u16(T.rec, o) * 2 + T.pageB - (tz - 2) + zstart;
        if (Math.floor(nw / 0x20000) !== page) throw "instrument crosses a page";
        put16(z, o, (nw / 2) & 0xffff);
      }
      setAddrs(z, T.sbOff, ...placed[k][i]);
      put16(z, T.sbOff - 2, tuneValue(zn.root, zn.cents, zn.rate) & 0xffff);
      inst.set(z, 4 + 6 * n + 2 + i * recLen);
    });
    out.set(inst, base);
    put32(out, 0xa6, FB + Math.floor((base + size + 1) / 2));
    const a = dirEntry(out, ...voiceToBankProg(banks, voice));
    out[a + 1] = page; put16(out, a + 2, (base / 2) & 0xffff);
  });
  return out;
}
function nameWords(voice, name, polish) {
  const s = name ? `${voice}.${name}` : "", cs = [...s];
  const bad = cs.filter(c => !(c >= " " && c <= "~" || polish && PL_LETTERS.includes(c)));
  if (bad.length) throw `name "${name}": the display has no ${bad.join("")}`;
  if (cs.length > 15) throw `name "${s}" too long (${cs.length} characters with the number, at most 15)`;
  return cs.map(c => c.codePointAt(0)).concat(Array(16 - cs.length).fill(0));
}
// entries: [{voice, name, name_pl}] into custom_voices' table of a patched DSP image (in place, fixes the checksum)
function fillNames(target, out, entries) {
  const v = target.voices;
  if (entries.length > v.max) throw `at most ${v.max} added instruments`;
  entries.forEach((e, i) => {
    const ws = [e.voice - 1].concat(nameWords(e.voice, e.name, false), nameWords(e.voice, e.name_pl || "", true));
    ws.forEach((w, j) => put16(out, 2 * (v.cvTab + i * 33 + j), w));
  });
  return fixChecksum(out);
}
// a bundled SoundFont's bytes, once its web/instruments/<id>.js has run
function packBytes(id) {
  const b64 = (globalThis.NUXDSP_PACK_DATA || {})[id];
  if (!b64) throw `instrument ${id} not loaded`;
  const s = atob(b64), out = new Uint8Array(s.length);
  for (let i = 0; i < s.length; i++) out[i] = s.charCodeAt(i);
  return out;
}
